spring:
  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    database: H2
    show-sql: true
    properties:
      hibernate:
#        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        query.in_clause_parameter_padding: true
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
#            sql: trace
